### ISSUE TITLE
Update the contribution doc

### ISSUE THREAD

**Issue by xofbd** [xofbd/wqu-s202101-project#1]
I copied over the contribution document from the fall 2020 session and I have forgotten to replace "fall 2002" with "spring 2021"

**Comment by 96RadhikaJadhav** [comment]
@xofbd Can I work on it?

**Comment by xofbd** [comment]
@96RadhikaJadhav Yes, you can. I'll assign you.

**Comment by py-mako** [comment]
I would like to work on the project when I have time. Could you add assign me also? I have been a part of the course.

**Comment by xofbd** [comment]
@py-mako Sure, find or open an issue and assign yourself.
